// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mais
{
    using System;
    using System.Reflection;

    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources
    {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.Equals(null, resourceMan))
                {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mais.Linguas.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        internal static string TextoEsqueciMinhaSenha
        {
            get
            {
                return ResourceManager.GetString("TextoEsqueciMinhaSenha", resourceCulture);
            }
        }

        internal static string TextoBotaoFinalizarEnquete
        {
            get
            {
                return ResourceManager.GetString("TextoBotaoFinalizarEnquete", resourceCulture);
            }
        }

        internal static string MensagemErroCadastroNovoUsuario
        {
            get
            {
                return ResourceManager.GetString("MensagemErroCadastroNovoUsuario", resourceCulture);
            }
        }

        internal static string TextoBotaoCancelarLogin
        {
            get
            {
                return ResourceManager.GetString("TextoBotaoCancelarLogin", resourceCulture);
            }
        }

        internal static string TextoPlaceHolderDDDCadastro
        {
            get
            {
                return ResourceManager.GetString("TextoPlaceHolderDDDCadastro", resourceCulture);
            }
        }

        internal static string TextoSucesso
        {
            get
            {
                return ResourceManager.GetString("TextoSucesso", resourceCulture);
            }
        }

        internal static string TextoVoltar
        {
            get
            {
                return ResourceManager.GetString("TextoVoltar", resourceCulture);
            }
        }

        internal static string MensagemSucessoCadastroNovoUsuario
        {
            get
            {
                return ResourceManager.GetString("MensagemSucessoCadastroNovoUsuario", resourceCulture);
            }
        }

        internal static string TextoBotaoCadastrar
        {
            get
            {
                return ResourceManager.GetString("TextoBotaoCadastrar", resourceCulture);
            }
        }

        internal static string TextoPlaceHolderTelefoneCadastro
        {
            get
            {
                return ResourceManager.GetString("TextoPlaceHolderTelefoneCadastro", resourceCulture);
            }
        }

        internal static string TextoPlaceholderTituloNaRespostaEnquete
        {
            get
            {
                return ResourceManager.GetString("TextoPlaceholderTituloNaRespostaEnquete", resourceCulture);
            }
        }

        internal static string TextoBotaoEsqueciMinhaSenha
        {
            get
            {
                return ResourceManager.GetString("TextoBotaoEsqueciMinhaSenha", resourceCulture);
            }
        }

        internal static string TextoPlaceHolderEmailCadastro
        {
            get
            {
                return ResourceManager.GetString("TextoPlaceHolderEmailCadastro", resourceCulture);
            }
        }

        internal static string TituloPaginaEnquete
        {
            get
            {
                return ResourceManager.GetString("TituloPaginaEnquete", resourceCulture);
            }
        }

        internal static string TextoParaBotaoResponderEnquete
        {
            get
            {
                return ResourceManager.GetString("TextoParaBotaoResponderEnquete", resourceCulture);
            }
        }

        internal static string TituloTabEnquetePublica
        {
            get
            {
                return ResourceManager.GetString("TituloTabEnquetePublica", resourceCulture);
            }
        }

        internal static string TextoPlaceHolderSenhaCadastro
        {
            get
            {
                return ResourceManager.GetString("TextoPlaceHolderSenhaCadastro", resourceCulture);
            }
        }

        internal static string TextoBotaoAdicionarResposta
        {
            get
            {
                return ResourceManager.GetString("TextoBotaoAdicionarResposta", resourceCulture);
            }
        }

        internal static string TextoPlaceHolderMunicipioCadastro
        {
            get
            {
                return ResourceManager.GetString("TextoPlaceHolderMunicipioCadastro", resourceCulture);
            }
        }

        internal static string MsgErroCadastroUsuario
        {
            get
            {
                return ResourceManager.GetString("MsgErroCadastroUsuario", resourceCulture);
            }
        }

        internal static string TextoCampoLoginFormLogin
        {
            get
            {
                return ResourceManager.GetString("TextoCampoLoginFormLogin", resourceCulture);
            }
        }

        internal static string TextoResetarSenha
        {
            get
            {
                return ResourceManager.GetString("TextoResetarSenha", resourceCulture);
            }
        }

        internal static string TextoMsgCadastroSucessoEnquete
        {
            get
            {
                return ResourceManager.GetString("TextoMsgCadastroSucessoEnquete", resourceCulture);
            }
        }

        internal static string TextoParaTelaDeVotoSalvoComSucesso
        {
            get
            {
                return ResourceManager.GetString("TextoParaTelaDeVotoSalvoComSucesso", resourceCulture);
            }
        }

        internal static string TextoPlaceHolderCategoriasCadastro
        {
            get
            {
                return ResourceManager.GetString("TextoPlaceHolderCategoriasCadastro", resourceCulture);
            }
        }

        internal static string TituloTabEnqueteInteresse
        {
            get
            {
                return ResourceManager.GetString("TituloTabEnqueteInteresse", resourceCulture);
            }
        }

        internal static string TextoPlaceholderTituloNaEnquete
        {
            get
            {
                return ResourceManager.GetString("TextoPlaceholderTituloNaEnquete", resourceCulture);
            }
        }

        internal static string TextoBotaoImportarAmigos
        {
            get
            {
                return ResourceManager.GetString("TextoBotaoImportarAmigos", resourceCulture);
            }
        }

        internal static string TextoCampoSenhaFormLogin
        {
            get
            {
                return ResourceManager.GetString("TextoCampoSenhaFormLogin", resourceCulture);
            }
        }

        internal static string MsgLoading
        {
            get
            {
                return ResourceManager.GetString("MsgLoading", resourceCulture);
            }
        }

        internal static string MsgErroCadastroUsuarioCamposEmBranco
        {
            get
            {
                return ResourceManager.GetString("MsgErroCadastroUsuarioCamposEmBranco", resourceCulture);
            }
        }

        internal static string TextoBotaoVoltarTelaLogin
        {
            get
            {
                return ResourceManager.GetString("TextoBotaoVoltarTelaLogin", resourceCulture);
            }
        }

        internal static string TextoPlaceHolderNomeCadastro
        {
            get
            {
                return ResourceManager.GetString("TextoPlaceHolderNomeCadastro", resourceCulture);
            }
        }

        internal static string MsgErroAoResponder
        {
            get
            {
                return ResourceManager.GetString("MsgErroAoResponder", resourceCulture);
            }
        }

        internal static string TituloErro
        {
            get
            {
                return ResourceManager.GetString("TituloErro", resourceCulture);
            }
        }

        internal static string TextoBotaoCriarConta
        {
            get
            {
                return ResourceManager.GetString("TextoBotaoCriarConta", resourceCulture);
            }
        }

        internal static string TextoSexoFeminino
        {
            get
            {
                return ResourceManager.GetString("TextoSexoFeminino", resourceCulture);
            }
        }

        internal static string TextoSexoMasculino
        {
            get
            {
                return ResourceManager.GetString("TextoSexoMasculino", resourceCulture);
            }
        }

        internal static string TextoSelecaoDuplicadaDeRespostaEnquente
        {
            get
            {
                return ResourceManager.GetString("TextoSelecaoDuplicadaDeRespostaEnquente", resourceCulture);
            }
        }

        internal static string TextoMsgCadastroErroEnquete
        {
            get
            {
                return ResourceManager.GetString("TextoMsgCadastroErroEnquete", resourceCulture);
            }
        }

        internal static string TextoBotaoSelecionarAmigos
        {
            get
            {
                return ResourceManager.GetString("TextoBotaoSelecionarAmigos", resourceCulture);
            }
        }

        internal static string TextoBotaoOKLogin
        {
            get
            {
                return ResourceManager.GetString("TextoBotaoOKLogin", resourceCulture);
            }
        }

        internal static string TextoPlaceHolderSexoCadastro
        {
            get
            {
                return ResourceManager.GetString("TextoPlaceHolderSexoCadastro", resourceCulture);
            }
        }

        internal static string TituloAviso
        {
            get
            {
                return ResourceManager.GetString("TituloAviso", resourceCulture);
            }
        }

        internal static string TextoMensagemLogin
        {
            get
            {
                return ResourceManager.GetString("TextoMensagemLogin", resourceCulture);
            }
        }

        internal static string TextoSucessoComVoucher
        {
            get
            {
                return ResourceManager.GetString("TextoSucessoComVoucher", resourceCulture);
            }
        }
    }
}
